# sudo: required
language: node_js

node_js:
    - "10"
    - "12"
cache:
  directories:
    - "node_modules"
git:
  depth: 5
addons:
  chromium: "latest"
before_script:
  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
before_install:
  - npm i -g npm@latest
  - npm install -g codecov
install:
  - npm i
script:
  - npm run test.nest.upms
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
after_success: npm run test.nest.upms.coverage
    
 

