sudo: false
# dist: xenial
language: node_js
node_js:
    - "10"
    - "12"
env:
  - DB=postgres10
  - DB=postgres11   
cache:
  directories:
    - "node_modules"   
git:
  depth: 5
services:
  - docker
  
# jobs:
#   include:
#     - stage: pgsql10
#       sudo: require
#       service: 
#         - docker    
#       before_script:
#         - bash ./testing/travis/install-postgres-10.sh
#     - stage pgsql11
#       sudo: require
#       service: 
#         - docker    
#       before_script:

#         - bash ./testing/travis/install-postgres-11.s
after_install
  - npm i -g npm@latest codecov
  - bash <(curl -s https://codecov.io/bash)
install:
  - npm i
before_install:
  - sh -c "if [ '$DB' = 'postgres10' ]; then bash ./testing/travis/install-postgres-10.sh; fi"
  - sh -c "if [ '$DB' = 'postgres10' ]; then bash ./testing/travis/install-postgres-11.sh; fi"  
script:
  - npm run test.nest.upms.e2e
#   - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
#   - codecov

  
after_success: npm run test.nest.upms.coverage
