sudo: false
# dist: xenial
language: node_js
# node_js:
#     - "10"
#     - "12"
cache:
  directories:
    - "node_modules"   
git:
  depth: 5
services:
  - docker
  
jobs:
  include:
  - stage: pgsql10
    sudo: require
    service: 
    - docker    
    before_script:
      - bash ./testing/travis/install-postgres-10.sh
  - stage pgsql11
    sudo: require
    service: 
    - docker    
    before_script:
      - bash ./testing/travis/install-postgres-11.sh
  
# #  - postgresql
# addons:
#   postgresql: "11"
#   apt:
#     packages:
#     - postgresql-11
#     - postgresql-client-11
# env:
#   global:
#     - PGPORT=5432
    # - PGDATABASE=test
    # - PGUSER=postgres
    # - PGHOST=localhost
    # - DB=postgres
  
before_script:
  # - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database test_ci;' -U postgres; echo $DB; fi"
  # - export DISPLAY=:99.0
  - bash ./testing/travis/install-postgres-11.sh
#   - sh -c "psql -c 'create database test_ci;' -U postgres;"
  - npm i -g npm@latest codecov

install:
  - npm i -g npm@latest codecov
  - npm i
script:
  - npm run test.nest.upms.e2e
#   - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
#   - codecov
after_script:
  - bash <(curl -s https://codecov.io/bash)
after_success: npm run test.nest.upms.coverage
