# sudo: required
language: node_js

node_js:
    - "10"
    - "12"
    
    
git:
  depth: 5
  
services:
  - postgresql
addons:
  postgresql: "10"
  chromium: "latest"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
cache:
  directories:
    - "node_modules"
  
before_script:
  - psql -U postgres -c "test"
  - export DISPLAY=:99.0

#  - sh -e /etc/init.d/xvfb start
before_install:
  - npm i -g npm@latest
  - npm install -g codecov
install:
  - npm i
script:
  - npm run test.nest.upms
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
after_success: npm run test.nest.upms.coverage
    
 

