projects:
  database:
    schemaPath: ../apps/nest-upms/src/prisma/prisma-types.graphql
    extensions:
      endpoints:
        default: http://192.168.1.238:4466
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: ../apps/nest-upms/src/prisma/prisma.binding.ts